app:ex3q1 ex3q2a ex3q2b ex3q3a ex3q3b

ex3q1:ex3q1.c
	gcc ex3q1.c -o ex3q1

ex3q2a:ex3q2a.c
	gcc ex3q2a.c -o ex3q2a

ex3q2b:ex3q2b.c
	gcc ex3q2b.c -o ex3q2b

ex3q3a:ex3q3a.c
	gcc ex3q3a.c -o ex3q3a

ex3q3b:ex3q3b.c
	gcc ex3q3b.c -o ex3q3b